services:
  db:
    image: mysql:8.0
    container_name: unistock_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: p5
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: unistock_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: unistock
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0

  worker:
    build: .
    container_name: unistock_worker
    restart: on-failure
    entrypoint: []
    command: celery -A backend worker -l info
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0

  beat:
    build: .
    container_name: unistock_beat
    restart: on-failure
    entrypoint: []
    command: celery -A backend beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: redis://redis:6379/0

volumes:
  mysql_data:
