# Generated by Django 6.0.3 on 2026-07-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notificacao_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
