# Generated by Django 6.0.3 on 2026-07-19 11:56

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_movimentacaoestoque_alter_itempedido_responsavel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email_ativo', models.BooleanField(default=True)),
                ('whatsapp_ativo', models.BooleanField(default=False)),
                ('telefone_whatsapp', models.CharField(blank=True, default='', max_length=20)),
                ('digest_ativo', models.BooleanField(default=False)),
                ('digest_horario', models.TimeField(default=datetime.time(18, 0))),
                ('digest_dias_semana', models.CharField(default='1,2,3,4,5', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencia_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
