# Generated by Django 6.0.3 on 2026-07-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_preferencianotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='estoque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='app.estoque'),
        ),
    ]
