# Generated by Django 6.0.3 on 2026-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_notificacao_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencianotificacao',
            name='ultimo_digest_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
