# Generated by Django 6.0.3 on 2026-07-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_digest_por_loja_7h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencianotificacao',
            name='digest_ativo',
        ),
        migrations.RemoveField(
            model_name='preferencianotificacao',
            name='digest_dias_semana',
        ),
        migrations.RemoveField(
            model_name='preferencianotificacao',
            name='digest_horario',
        ),
        migrations.RemoveField(
            model_name='preferencianotificacao',
            name='ultimo_digest_em',
        ),
    ]
