# Generated by Django 6.0.3 on 2026-09-21 14:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_fabrica_e_caixas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('passo', models.CharField(choices=[('A_CAMINHO', 'A caminho'), ('CHEGOU', 'Chegou'), ('ABERTA', 'Aberta'), ('ACABOU', 'Acabou')], max_length=10)),
                ('desfeita_em', models.DateTimeField(blank=True, null=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='app.caixa')),
                ('caixa_fechada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app.caixa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_de_caixa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
